
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build (si aplica)
        run: npm run build || echo "No build step"

      # Aquí falta el paso de deploy, ejemplo con Koyeb CLI:
      #- name: Install Koyeb CLI
      #  run: curl -sSL https://cli.koyeb.com/install.sh | sh
      #
      #- name: Authenticate Koyeb CLI
      #  env:
      #    KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
      #  run: koyeb login --api-token $KOYEB_API_TOKEN
      #
      #- name: Deploy to Koyeb
      #  run: koyeb service update --service your-service-name --image your-image-name:tag
